#!/bin/bash
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=${TMPDIR:-/tmp}

destination="$1"

if [ -z "${destination}" ]; then
  echo "Usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload="$(mktemp "${TMPDIR}/gitlab-cf-diff-delete-resource.XXXXXX")"

cat > "${payload}" <&0

version="$(jq -r '.version // ""' < "${payload}")"
target_app="$(echo "${version}" | jq -r '.app // ""')"

cd "${destination}"
mkdir "${destination}"
cd "${destination}"
echo "${target_app}" > appname.txt

jq -n "{
    version: ${version}
}" >&3
